{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "builder-model",
    "version": "8.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "builder-model-8.1.3.jar",
          "url": "builder-model-8.1.3.jar",
          "size": 113984,
          "sha512": "03ba48155ffbfa2633c8307811d33955ca0f69029abffef0694ea5d6a74a594bd52a3c5c7b97bb5a1cfed3eb555e4d2ffe090c6069df649b0912d8ff4f39a53b",
          "sha256": "66e6cafa50700256f44acad2a6a8c451849d52c333fe7353beb325f503219c7d",
          "sha1": "1698e7cd9c17bdc006c020b4e9c014614a5236fe",
          "md5": "26627eb0f2cabfbaabe0ca5c599003c0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools",
          "module": "annotations",
          "version": {
            "requires": "31.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20-RC2"
          }
        }
      ],
      "files": [
        {
          "name": "builder-model-8.1.3.jar",
          "url": "builder-model-8.1.3.jar",
          "size": 113984,
          "sha512": "03ba48155ffbfa2633c8307811d33955ca0f69029abffef0694ea5d6a74a594bd52a3c5c7b97bb5a1cfed3eb555e4d2ffe090c6069df649b0912d8ff4f39a53b",
          "sha256": "66e6cafa50700256f44acad2a6a8c451849d52c333fe7353beb325f503219c7d",
          "sha1": "1698e7cd9c17bdc006c020b4e9c014614a5236fe",
          "md5": "26627eb0f2cabfbaabe0ca5c599003c0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "builder-model-8.1.3-javadoc.jar",
          "url": "builder-model-8.1.3-javadoc.jar",
          "size": 290907,
          "sha512": "8206140d0d91b919dca0d38c5f9b5ef33ffa7c8e952835e31a9487fb3101e810a317383b4c5225abd87bc6c97632d12bf5bb227c0330298d0a6a7fa1709d12c8",
          "sha256": "26a9ac2a7bde16a3ad594251c41f097dc9b6e6d78e2597d2145934884ea0b20f",
          "sha1": "840a40119124be207e07cf4164234cea76f74d0b",
          "md5": "f54c8e7f303816e812cb763c987ccc5a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "builder-model-8.1.3-sources.jar",
          "url": "builder-model-8.1.3-sources.jar",
          "size": 140439,
          "sha512": "bd1c1107fcba15f60465894fa2fdc12ccfd6138475b9a749a09ff599b23712dc75ca4b91edeb556d5c05aebff84f25d7dea0f3740c210d56335b2acbc3b0d01e",
          "sha256": "fccfc20aef29d5e2c1e746e44d7194b28d13bb8e8232ad2d4d7b89e435822e60",
          "sha1": "a9f473117133f6e0f1eb8c4f2c514cb44911801e",
          "md5": "6e3e65e51af37eeb44a040347a84cf7a"
        },
        {
          "name": "builder-model-8.1.3-sources.jar",
          "url": "builder-model-8.1.3-sources.jar",
          "size": 140439,
          "sha512": "bd1c1107fcba15f60465894fa2fdc12ccfd6138475b9a749a09ff599b23712dc75ca4b91edeb556d5c05aebff84f25d7dea0f3740c210d56335b2acbc3b0d01e",
          "sha256": "fccfc20aef29d5e2c1e746e44d7194b28d13bb8e8232ad2d4d7b89e435822e60",
          "sha1": "a9f473117133f6e0f1eb8c4f2c514cb44911801e",
          "md5": "6e3e65e51af37eeb44a040347a84cf7a"
        }
      ]
    }
  ]
}
