{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.camera",
    "module": "camera-lifecycle",
    "version": "1.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3-rc-1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.3.1"
          },
          "reason": "camera-lifecycle is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.3.1"
          },
          "reason": "camera-lifecycle is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-extensions",
          "version": {
            "requires": "1.3.1"
          },
          "reason": "camera-lifecycle is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-video",
          "version": {
            "requires": "1.3.1"
          },
          "reason": "camera-lifecycle is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.3.1"
          },
          "reason": "camera-lifecycle is in atomic group androidx.camera"
        }
      ],
      "files": [
        {
          "name": "camera-lifecycle-1.3.1.aar",
          "url": "camera-lifecycle-1.3.1.aar",
          "size": 22530,
          "sha512": "9271e516f0eb4a2f608a787db13154ef51879f053891f8917101e0a1454d74ab85bf3a6773733129b8010ec366f5c75063cc6ce35ca04f00ca6cc5025ecabc44",
          "sha256": "ef5cf75cec6a5c72f6231860ae9ba835393e881a4c37938777d9469dee22a4b6",
          "sha1": "f092bb2053146082c3caac18b630196dc2ff0265",
          "md5": "6bbd0ad114802901aeb0eb9782cf4ec0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.google.auto.value",
          "module": "auto-value-annotations",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.3.1"
          },
          "reason": "camera-lifecycle is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.3.1"
          },
          "reason": "camera-lifecycle is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-extensions",
          "version": {
            "requires": "1.3.1"
          },
          "reason": "camera-lifecycle is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-video",
          "version": {
            "requires": "1.3.1"
          },
          "reason": "camera-lifecycle is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.3.1"
          },
          "reason": "camera-lifecycle is in atomic group androidx.camera"
        }
      ],
      "files": [
        {
          "name": "camera-lifecycle-1.3.1.aar",
          "url": "camera-lifecycle-1.3.1.aar",
          "size": 22530,
          "sha512": "9271e516f0eb4a2f608a787db13154ef51879f053891f8917101e0a1454d74ab85bf3a6773733129b8010ec366f5c75063cc6ce35ca04f00ca6cc5025ecabc44",
          "sha256": "ef5cf75cec6a5c72f6231860ae9ba835393e881a4c37938777d9469dee22a4b6",
          "sha1": "f092bb2053146082c3caac18b630196dc2ff0265",
          "md5": "6bbd0ad114802901aeb0eb9782cf4ec0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.3.1"
          },
          "reason": "camera-lifecycle is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.3.1"
          },
          "reason": "camera-lifecycle is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-extensions",
          "version": {
            "requires": "1.3.1"
          },
          "reason": "camera-lifecycle is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-video",
          "version": {
            "requires": "1.3.1"
          },
          "reason": "camera-lifecycle is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.3.1"
          },
          "reason": "camera-lifecycle is in atomic group androidx.camera"
        }
      ],
      "files": [
        {
          "name": "camera-lifecycle-1.3.1-sources.jar",
          "url": "camera-lifecycle-1.3.1-sources.jar",
          "size": 19479,
          "sha512": "99b47bbc7e73be98edc3bf398ba7f6258c388699aa5643aefe24d95275e8428da6ae33a59cd7c387cebcfe5a78aef6d3cc45495421cd19a08fc4aec52c6f67ed",
          "sha256": "d9b8215f54dbb15ed6fffcdfe96cc436fc3897e77c73a2ff986210ba3ebfbd32",
          "sha1": "fadc8569bbf7f44a7a5425643064db16fdd0c131",
          "md5": "4fcb231a866441ec8bbd6253fe25545c"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.3.1"
          },
          "reason": "camera-lifecycle is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.3.1"
          },
          "reason": "camera-lifecycle is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-extensions",
          "version": {
            "requires": "1.3.1"
          },
          "reason": "camera-lifecycle is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-video",
          "version": {
            "requires": "1.3.1"
          },
          "reason": "camera-lifecycle is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.3.1"
          },
          "reason": "camera-lifecycle is in atomic group androidx.camera"
        }
      ],
      "files": [
        {
          "name": "camera-lifecycle-1.3.1-versionMetadata.json",
          "url": "camera-lifecycle-1.3.1-versionMetadata.json",
          "size": 1358,
          "sha512": "d6b649536a6f268e349631cd59b3a8c49902525ebc5f9c40523feb73e6f0e1488c4c9820718e47fa5c9eec829061bea72556c37f317a0351a2d453a12602c15c",
          "sha256": "dec47a1225c39669f211d4ca433401b144d71c4e66064fc677aaf37bc72e83d2",
          "sha1": "e50d375a33899673fc11269329781bcb4a70fce0",
          "md5": "743229b0e0a24f78507bc9dddcca3d3c"
        }
      ]
    }
  ]
}