{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "gradle-api",
    "version": "8.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-api-8.1.3.jar",
          "url": "gradle-api-8.1.3.jar",
          "size": 287212,
          "sha512": "9604c57e51b6f6b148fab8767e120cb606ca949c615c49653d9dc3ec3f82f0ec2c62e64f29a1ecddd32a9e91f00e6436aa83f2017810c3f91d77c7003b5eed02",
          "sha256": "5350200b8d89b7a4f0fc60d31d9f35b199d6bd0085360e5779e9c4d0b319d315",
          "sha1": "256a444803f11a787cd42242b6282a94dde3cad1",
          "md5": "d3cd2dfe54c92346b9748abb867dee88"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "builder-test-api",
          "version": {
            "requires": "8.1.3"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "31.1-jre"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20-RC2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-api-8.1.3.jar",
          "url": "gradle-api-8.1.3.jar",
          "size": 287212,
          "sha512": "9604c57e51b6f6b148fab8767e120cb606ca949c615c49653d9dc3ec3f82f0ec2c62e64f29a1ecddd32a9e91f00e6436aa83f2017810c3f91d77c7003b5eed02",
          "sha256": "5350200b8d89b7a4f0fc60d31d9f35b199d6bd0085360e5779e9c4d0b319d315",
          "sha1": "256a444803f11a787cd42242b6282a94dde3cad1",
          "md5": "d3cd2dfe54c92346b9748abb867dee88"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradle-api-8.1.3-javadoc.jar",
          "url": "gradle-api-8.1.3-javadoc.jar",
          "size": 150993,
          "sha512": "29684a399e3a5eba0223251b1a1ca65c5605a89cfc7493f7e1d869000dbbe469fa186072b1464638f9a8d2b2da850c38c8e1d3233e2e388d8f54eadd500cc8e9",
          "sha256": "6833485c9e33acd8972a8ef9fb523aa6b911f138e03870bee5ddcfd382a81f80",
          "sha1": "f06e3c70e4839c2f0b3c329452868ef7a08e5c5f",
          "md5": "5dab3433fbf138d36621bb31fddcc3d4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradle-api-8.1.3-sources.jar",
          "url": "gradle-api-8.1.3-sources.jar",
          "size": 285107,
          "sha512": "fbde89bacec711b7952bfcb7f1d5e1294413d6cce100d01f5de4cd0858b1af325e83335f660af56b3c4243f5a7e8f899c76fc8a661ffb8ed9688c5b9e6d4e6a6",
          "sha256": "b11df8f399f38af595c84b9d122def1492ef0391ea7aeb0897a496daf7a19594",
          "sha1": "fc9db61dfa97d5b5c107eb4ae59f12e0f286a070",
          "md5": "5680889f4ac1e897131acbc8750ddc95"
        },
        {
          "name": "gradle-api-8.1.3-sources.jar",
          "url": "gradle-api-8.1.3-sources.jar",
          "size": 285107,
          "sha512": "fbde89bacec711b7952bfcb7f1d5e1294413d6cce100d01f5de4cd0858b1af325e83335f660af56b3c4243f5a7e8f899c76fc8a661ffb8ed9688c5b9e6d4e6a6",
          "sha256": "b11df8f399f38af595c84b9d122def1492ef0391ea7aeb0897a496daf7a19594",
          "sha1": "fc9db61dfa97d5b5c107eb4ae59f12e0f286a070",
          "md5": "5680889f4ac1e897131acbc8750ddc95"
        }
      ]
    }
  ]
}
