{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ui-tooling-preview/1.6.0/ui-tooling-preview-1.6.0.module",
    "group": "androidx.compose.ui",
    "module": "ui-tooling-preview",
    "version": "1.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.0"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.6.0"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.6.0"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.6.0"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.6.0"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest",
          "version": {
            "requires": "1.6.0"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.6.0"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.6.0"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.6.0"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.6.0"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.6.0"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.6.0"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.6.0"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        }
      ],
      "files": [
        {
          "name": "ui-tooling-preview-release.aar",
          "url": "ui-tooling-preview-android-1.6.0.aar",
          "size": 17210,
          "sha512": "b6712903803af0e3207fc6b0a6bbeea33770597109e8d86cfcc179eae93d9e362447efab50b1ea1b0d2b8b6bae108a824809b65679cd33e93605ae376b34f952",
          "sha256": "ed7a5900405d8561bbddaa02bd3e38408c12de00bb942bd32c4fcbb9ba7b2ece",
          "sha1": "ea4abddba6bb3f08d5d22b30985fe59610de309c",
          "md5": "220f5cf4e567ebd2323453695614475a"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.0"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.6.0"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.6.0"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.6.0"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.6.0"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest",
          "version": {
            "requires": "1.6.0"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.6.0"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.6.0"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.6.0"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.6.0"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.6.0"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.6.0"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.6.0"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        }
      ],
      "files": [
        {
          "name": "ui-tooling-preview-release.aar",
          "url": "ui-tooling-preview-android-1.6.0.aar",
          "size": 17210,
          "sha512": "b6712903803af0e3207fc6b0a6bbeea33770597109e8d86cfcc179eae93d9e362447efab50b1ea1b0d2b8b6bae108a824809b65679cd33e93605ae376b34f952",
          "sha256": "ed7a5900405d8561bbddaa02bd3e38408c12de00bb942bd32c4fcbb9ba7b2ece",
          "sha1": "ea4abddba6bb3f08d5d22b30985fe59610de309c",
          "md5": "220f5cf4e567ebd2323453695614475a"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.0"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.6.0"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.6.0"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.6.0"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.6.0"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest",
          "version": {
            "requires": "1.6.0"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.6.0"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.6.0"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.6.0"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.6.0"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.6.0"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.6.0"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.6.0"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        }
      ],
      "files": [
        {
          "name": "ui-tooling-preview-android-1.6.0-sources.jar",
          "url": "ui-tooling-preview-android-1.6.0-sources.jar",
          "size": 11399,
          "sha512": "38560bdd4d5584a75a81b34fcc5cfd97ba6611d19fb9112b58e500aa87d6aae15c789c1edb99a8233df3337a2079c1e6f2e0161375136e069aa7863f7e6edd3c",
          "sha256": "656eba588959145bdea9b2bd67fe5c7a3ae685093ed69491d64698c81a70faa7",
          "sha1": "c1cc66505a91b370b6f456d88ab4eba3400300f7",
          "md5": "cb00e2d6aefd162943639320f8dfcd8e"
        }
      ]
    }
  ]
}