{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.runtime",
    "module": "runtime",
    "version": "1.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "androidxSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "androidx-multiplatform-docs"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava3",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-1.5.1-multiplatform-sources.jar",
          "url": "runtime-1.5.1-multiplatform-sources.jar",
          "size": 342173,
          "sha512": "9fdde2eb36840bb6f95394638800103d3fe5340bb0941c49748f801ed83aa56fb40438cecd4be7a54326373ef67fcd97d79922fbd07629c8627da7f300ed81ef",
          "sha256": "08ebb1d580445b97363a9e9f1f36d8a681677b4aab29359520324cdcd99202a1",
          "sha1": "533aed15d00d99dbcadff244640f0da4367a95f5",
          "md5": "4bb829db0b7f238a44860c394896b81a"
        }
      ]
    },
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava3",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-metadata-1.5.1.jar",
          "url": "runtime-1.5.1.jar",
          "size": 660,
          "sha512": "b2f9847ad3b9e240fe027dd4b7bae0977964c709907294254b4906a8a4786c1c7b4d1d191aa7593985c5baac302772dcbf2933dc7173324ab645131182260d53",
          "sha256": "1dd30ce8cca076140ed92ee748c1d35a4ac46b9da435406e353208a07267996d",
          "sha1": "b5c589b0e46d99e25aebe48839215aaec925ae55",
          "md5": "ba41245ca2b526249e40016327115655"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava3",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-kotlin-1.5.1-sources.jar",
          "url": "runtime-1.5.1-sources.jar",
          "size": 321504,
          "sha512": "c59b6fb4c2fe3606d9514ad49e77345d80002ef6bf32bdbd735d00bba0ec7facce1a42a53d0b762a5aab82a1219be7c9ac5f5d5c0a4534ffce5b58e6b5aa1e69",
          "sha256": "2dc25b1d1e58d10bf4e451649c3b5a510e1a4bb09de38c852c56f8a485ee481a",
          "sha1": "dc143e51205bc827936124e033c0db0fc1b58e48",
          "md5": "081024992132c21b63c8ce865944a8c1"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../runtime-android/1.5.1/runtime-android-1.5.1.module",
        "group": "androidx.compose.runtime",
        "module": "runtime-android",
        "version": "1.5.1"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../runtime-android/1.5.1/runtime-android-1.5.1.module",
        "group": "androidx.compose.runtime",
        "module": "runtime-android",
        "version": "1.5.1"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../runtime-android/1.5.1/runtime-android-1.5.1.module",
        "group": "androidx.compose.runtime",
        "module": "runtime-android",
        "version": "1.5.1"
      }
    }
  ]
}