{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.compiler",
    "module": "compiler",
    "version": "1.5.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.compiler",
          "module": "compiler-hosted",
          "version": {
            "requires": "1.5.8"
          },
          "reason": "compiler is in atomic group androidx.compose.compiler"
        }
      ],
      "files": [
        {
          "name": "compiler-1.5.8.jar",
          "url": "compiler-1.5.8.jar",
          "size": 1115112,
          "sha512": "2cde288e2a08f74890ea54018081ba24b2efe421e231e5b7bfbb68b0bd841d3fa6d83b077a48a0a19e7869f5c7b48946d0e025088244ec65003851515cca2bdd",
          "sha256": "ab62f666a2b17dc7432c1619457a951b062f4c5320d6b2e1eea53f39daae95ee",
          "sha1": "b6b82a47735d855ae7050d1aa2f026dfeedaf635",
          "md5": "00201ff4af32eff81b5d1d9acf297cf8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.compiler",
          "module": "compiler-hosted",
          "version": {
            "requires": "1.5.8"
          },
          "reason": "compiler is in atomic group androidx.compose.compiler"
        }
      ],
      "files": [
        {
          "name": "compiler-1.5.8.jar",
          "url": "compiler-1.5.8.jar",
          "size": 1115112,
          "sha512": "2cde288e2a08f74890ea54018081ba24b2efe421e231e5b7bfbb68b0bd841d3fa6d83b077a48a0a19e7869f5c7b48946d0e025088244ec65003851515cca2bdd",
          "sha256": "ab62f666a2b17dc7432c1619457a951b062f4c5320d6b2e1eea53f39daae95ee",
          "sha1": "b6b82a47735d855ae7050d1aa2f026dfeedaf635",
          "md5": "00201ff4af32eff81b5d1d9acf297cf8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.compiler",
          "module": "compiler-hosted",
          "version": {
            "requires": "1.5.8"
          },
          "reason": "compiler is in atomic group androidx.compose.compiler"
        }
      ],
      "files": [
        {
          "name": "compiler-1.5.8-sources.jar",
          "url": "compiler-1.5.8-sources.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}