{
  "formatVersion": "1.1",
  "component": {
    "group": "com.google.devtools.ksp",
    "module": "symbol-processing-common-deps",
    "version": "1.9.22-1.0.17",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "symbol-processing-common-deps-1.9.22-1.0.17.jar",
          "url": "symbol-processing-common-deps-1.9.22-1.0.17.jar",
          "size": 24297,
          "sha512": "1a67ccbde06929bc774c6b0d6576b9468fefb84b0fc6a0bb4b4cd540d4c7efd72321eddaead789c6c8ccbd243d8875f949296e897364d70bbeb4aa9f01567e2d",
          "sha256": "b481df3ceee2dfc28b16c2854c7242b4a4174a1495aca050f37fc4f90cefe588",
          "sha1": "ad200f37e67b88e5f9f90ed63f5d92c21c95bc1b",
          "md5": "06162c019f907a23f800e269080db355"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "symbol-processing-common-deps-1.9.22-1.0.17.jar",
          "url": "symbol-processing-common-deps-1.9.22-1.0.17.jar",
          "size": 24297,
          "sha512": "1a67ccbde06929bc774c6b0d6576b9468fefb84b0fc6a0bb4b4cd540d4c7efd72321eddaead789c6c8ccbd243d8875f949296e897364d70bbeb4aa9f01567e2d",
          "sha256": "b481df3ceee2dfc28b16c2854c7242b4a4174a1495aca050f37fc4f90cefe588",
          "sha1": "ad200f37e67b88e5f9f90ed63f5d92c21c95bc1b",
          "md5": "06162c019f907a23f800e269080db355"
        }
      ]
    }
  ]
}
