{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.databinding",
    "module": "viewbinding",
    "version": "8.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "viewbinding-8.1.3.aar",
          "url": "viewbinding-8.1.3.aar",
          "size": 1834,
          "sha512": "da0ae29a0849a92112110dc717cd0f4856481784614e41201d73f7760a4de8e2a07f3fa4395a2a3f508ebb05e647a7a785fbcc6e20e9190b01395faaa9118a69",
          "sha256": "f90dfdda5d55ab5fd34a3f8de2eeff1f284513ee8bb890bf10a2a3e0714d67b5",
          "sha1": "c762d91504cf6443f75db41a27bdd4e651724c60",
          "md5": "84a8d47ab9c26fc56dad262b784d374a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "viewbinding-8.1.3.aar",
          "url": "viewbinding-8.1.3.aar",
          "size": 1834,
          "sha512": "da0ae29a0849a92112110dc717cd0f4856481784614e41201d73f7760a4de8e2a07f3fa4395a2a3f508ebb05e647a7a785fbcc6e20e9190b01395faaa9118a69",
          "sha256": "f90dfdda5d55ab5fd34a3f8de2eeff1f284513ee8bb890bf10a2a3e0714d67b5",
          "sha1": "c762d91504cf6443f75db41a27bdd4e651724c60",
          "md5": "84a8d47ab9c26fc56dad262b784d374a"
        }
      ]
    }
  ]
}
