{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.camera",
    "module": "camera-video",
    "version": "1.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3-rc-1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.3.1"
          },
          "reason": "camera-video is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.3.1"
          },
          "reason": "camera-video is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-extensions",
          "version": {
            "requires": "1.3.1"
          },
          "reason": "camera-video is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.3.1"
          },
          "reason": "camera-video is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.3.1"
          },
          "reason": "camera-video is in atomic group androidx.camera"
        }
      ],
      "files": [
        {
          "name": "camera-video-1.3.1.aar",
          "url": "camera-video-1.3.1.aar",
          "size": 361506,
          "sha512": "b84450b920213a58b169a2b509563ed8107573bd37afb3509c519e8f2e58fdb915a34d9d9bc013f6d0895513fb8f5bb6e4aaaf3e550449e599e936a79559a981",
          "sha256": "8b2a859ec155ce473ca701a72fe1b6c93e875c79089bba0d5734c2170beeea7d",
          "sha1": "d4dfdc45b26ebd3c4b961f162a649ea8502e20b9",
          "md5": "7982fae42bc075f4dba330cf3d6e8169"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.auto.value",
          "module": "auto-value-annotations",
          "version": {
            "requires": "1.6.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.3.1"
          },
          "reason": "camera-video is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.3.1"
          },
          "reason": "camera-video is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-extensions",
          "version": {
            "requires": "1.3.1"
          },
          "reason": "camera-video is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.3.1"
          },
          "reason": "camera-video is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.3.1"
          },
          "reason": "camera-video is in atomic group androidx.camera"
        }
      ],
      "files": [
        {
          "name": "camera-video-1.3.1.aar",
          "url": "camera-video-1.3.1.aar",
          "size": 361506,
          "sha512": "b84450b920213a58b169a2b509563ed8107573bd37afb3509c519e8f2e58fdb915a34d9d9bc013f6d0895513fb8f5bb6e4aaaf3e550449e599e936a79559a981",
          "sha256": "8b2a859ec155ce473ca701a72fe1b6c93e875c79089bba0d5734c2170beeea7d",
          "sha1": "d4dfdc45b26ebd3c4b961f162a649ea8502e20b9",
          "md5": "7982fae42bc075f4dba330cf3d6e8169"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.3.1"
          },
          "reason": "camera-video is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.3.1"
          },
          "reason": "camera-video is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-extensions",
          "version": {
            "requires": "1.3.1"
          },
          "reason": "camera-video is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.3.1"
          },
          "reason": "camera-video is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.3.1"
          },
          "reason": "camera-video is in atomic group androidx.camera"
        }
      ],
      "files": [
        {
          "name": "camera-video-1.3.1-sources.jar",
          "url": "camera-video-1.3.1-sources.jar",
          "size": 262785,
          "sha512": "a604c3567164066cd505bb76bd0c15937977e3c68ccd3f85f6b772bce10610b2a0ef00872e8e699c16d06849c78ecc6bf5c9dec9e0a00a1b64fc83c0574dfbe9",
          "sha256": "b550fd75244b2cc11a76d1d6f7556a37fe0788971e3a83a5a1924ff05288dd70",
          "sha1": "744f04a0efc95a4c086127d37f550e80450a2bc1",
          "md5": "3d35f456cee452a89516f4b40c8b97ed"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.3.1"
          },
          "reason": "camera-video is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.3.1"
          },
          "reason": "camera-video is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-extensions",
          "version": {
            "requires": "1.3.1"
          },
          "reason": "camera-video is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.3.1"
          },
          "reason": "camera-video is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.3.1"
          },
          "reason": "camera-video is in atomic group androidx.camera"
        }
      ],
      "files": [
        {
          "name": "camera-video-1.3.1-versionMetadata.json",
          "url": "camera-video-1.3.1-versionMetadata.json",
          "size": 10368,
          "sha512": "4ceba0b20c5e182ccb5f30fee7eed5b13bf86b08d6dccf8e09ee3fcb1472a1d4e58124aa5bc945771a0d44038b4fe4bd1af8f5c0ba4b3699bce7617f70ee1662",
          "sha256": "8aafdb0d034395a7800f5bcc96a57cf738dcf17811680fc7bdf158d056c8f6cb",
          "sha1": "ebe9755a7b17468d03231fad35bd8d4dcefef0a2",
          "md5": "b684bc2c6353f9aaf766ec75e644a7b3"
        }
      ]
    }
  ]
}