name: SmartSearch CI Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_apk:
    runs-on: ubuntu-latest
    env:
      ANDROID_SDK_ROOT: ${{ github.workspace }}/android_sdk
      JAVA_VERSION: 17

    steps:
      - name: 拉取项目源码
        uses: actions/checkout@v4

      - name: 配置JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: temurin

      # 关键：强制生成gradle包装脚本，不存在也能创建
      - name: 生成 gradlew 脚本
        run: gradle wrapper --gradle-version=8.13

      # 现在文件已经生成，可以授权权限
      - name: 授权gradlew执行权限
        run: chmod +x gradlew

      - name: 下载 Android CommandLineTools
        run: wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O commandlinetools.zip

      - name: 解压配置SDK
        run: |
          unzip commandlinetools.zip
          mkdir -p $ANDROID_SDK_ROOT/cmdline-tools
          mv cmdline-tools $ANDROID_SDK_ROOT/cmdline-tools/latest

      - name: 同意SDK许可证
        run: yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --licenses

      - name: 安装SDK编译工具
        run: $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager "platforms;android-34" "build-tools;34.0.0"

      - name: 编译Release安装包
        run: ./gradlew assembleRelease

      - name: 上传APK产物
        uses: actions/upload-artifact@v4
        with:
          name: 离线搜题APK
          path: app/build/outputs/apk/release/*.apk
