name: SmartSearch打包
on:
  push: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      JAVA_HOME: ${{ steps.java.outputs.java-home }}
    steps:
      - name: 拉取源码
        uses: actions/checkout@v4

      - name: 配置JDK17
        id: java
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      # 自动下载完整官方gradlew，修复缺失/损坏wrapper
      - name: Fix Gradle Wrapper
        run: |
          wget https://services.gradle.org/distributions/gradle-8.13-all.zip -O gradle.zip
          mkdir temp_gradle
          unzip gradle.zip -d temp_gradle
          cp temp_gradle/gradle-8.13/gradlew ./
          cp -r temp_gradle/gradle-8.13/gradle/wrapper ./gradle/
          chmod +x gradlew

      # 安装安卓SDK
      - name: Install Android SDK
        run: |
          mkdir -p ~/android-sdk/cmdline-tools/latest
          wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O sdk.zip
          unzip sdk.zip -d ~/android-sdk/cmdline-tools/latest
          export PATH=$PATH:~/android-sdk/cmdline-tools/latest/bin
          yes | sdkmanager --licenses
          sdkmanager "platforms;android-34" "build-tools;34.0.0"
        env:
          ANDROID_SDK_ROOT: ~/android-sdk

      # 编译Release包
      - name: Build APK
        run: ./gradlew assembleRelease
        env:
          ANDROID_SDK_ROOT: ~/android-sdk

      # 上传安装包
      - name: 导出APK
        uses: actions/upload-artifact@v4
        with:
          name: 搜题APP安装包
          path: app/build/outputs/apk/release/*.apk
